config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about' => 'home#about'
  get 'search' => 'searches#search'
  get 'searches/search'
  get 'chat/:id' => 'chat#show', as: 'chat'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :chats, only: [:create]

  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:destroy, :create]
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
  	@book = Book.find(params[:book_id])
  	favorite = current_user.favorites.new(book_id: @book.id)
  	favorite.save
  end

  def destroy
  	@book = Book.find(params[:book_id])
  	favorite = current_user.favorites.find_by(book_id: @book.id)
  	favorite.destroy
    @book.favorites.where( user_id: current_user.id ).exists?
  end
end

#

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(user) %>
<li>
    <%= link_to book_favorites_path(book.id), method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %> いいね
    <% end %>
</li>
<% else %>
<li>
    <%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <%= book.favorites.count %> いいね
    <% end %>
</li>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render 'favorites/favorite', book: @book, user: current_user) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render 'favorites/favorite', book: @book, user: current_user) %>");