config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about' => 'home#about'
  get 'search' => 'searches#search'
  get 'searches/search'
  get 'chat/:id' => 'chat#show', as: 'chat'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :chats, only: [:create]

  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:destroy, :create]
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

# バリデーション
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  # validates :postcode, presence: true
  # validates :prefecture_code, presence: true
  # validates :city, presence: true
  # validates :street, presence: true
# バリデーション

# アソシエーション
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id",
                                     class_name: "Relationship",
                                     dependent: :destroy
  has_many :follower_relationships, foreign_key: "following_id",
                                    class_name: "Relationship",
                                    dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :followers, through: :follower_relationships
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
# アソシエーション


# follow関連
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
# follow関連


  def self.search(search, word)
    if search == "perfect_match"
      @user = User.where(name: "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    else
      @user = User.all
    end
  end

  include JpPrefecture
  jp_prefecture :prefecture_code
  # def prefecture_name
  #   JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  # end

  # def prefecture_name=(prefecture_name)
  #   self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  # end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    # build_resource(sign_up_params)

    # resource.save
    # yield resource if block_given?
    # if resource.persisted?
    #   if resource.active_for_authentication?
    #     set_flash_message! :notice, :signed_up
    #     sign_up(resource_name, resource)
    #     respond_with resource, location: after_sign_up_path_for(resource)
    #     ThanksMailer.send_mail(current_user).deliver_now
    #   else
    #     set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
    #     expire_data_after_sign_in!
    #     respond_with resource, location: after_inactive_sign_up_path_for(resource)
    #   end
    # else
    #   clean_up_passwords resource
    #   set_minimum_password_length
    #   respond_with resource
    # end
    super
    # ThanksMailer.send_mail(current_user).deliver_now
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user?, only: [:edit, :update]

  def ensure_current_user?
    user = User.find(params[:id])
    redirect_to user_path(current_user) unless user == current_user
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/ _unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(user) %>
  <div id="follow_form">
    <% if current_user.following?(user) %>
      <%= link_to "Unfollow", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "Forrow", user_relationships_path(user.id), method: :POST, class: "btn btn-success" %>
    <% end %>
  </div>
<% end %>

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <th><p><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "noimage.png", size:'40' %></p></th>
      <th><%= user.name %></th>
      <th><%= "フォロー数#{user.followings.count}" %></th>
      <th><%= "フォロワー数#{user.followers.count}" %></th>
      <th>
        <%= render 'follow_form', user: user %>
      </th>
      <th><%= link_to "Show", user_path(user) %></th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class="table">
  <tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "noimage.png", size:'100x100' %></tr>
  <tr>
    <th>name</th>
    <td><%= user.name %></td>
  </tr>
  <tr>
    <th>introduction</th>
    <td><%= user.introduction %></td>
  </tr>
  <tr>
    <th>following</th>
    <td><%= link_to user.followings.count, following_user_path(user) %></td>
  </tr>
  <tr>
    <th>followers</th>
    <td><%= link_to user.followers.count, followers_user_path(user) %></td>
  </tr>
  <tr>
    <td><%= render 'users/follow_form', user: user %></td>
  </tr>
</table>

<% if current_user != user %>
  <%= link_to "Let's Chat", chat_path(user.id) %>
<% end %>

<% if user == current_user %>
  <div class="row">
    <p><%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %></p>
  </div>
<% end %>

app/views/users/_stats.html.erb
<% user ||= current_user %>
<div class="stats">
  <tr>
    <th>following</th>
    <td><%= link_to user.followings.count, following_user_path(user) %></td>
  </tr>
  <tr>
    <th>followers</th>
    <td><%= link_to user.followers.count, followers_user_path(user) %></td>
  </tr>
</div>

app/views/users/edit.html.erb
		<%= form_for(@user, url: user_path(@user.id)) do |f| %>
		<h2>User info</h2>

		<% if @user.errors.any? %>
			<div id="error_explanation">
   				<h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
				<ul>
					<% @user.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

			<%= f.label :Name %>
			<%= f.text_field :name, class: "mb-10px" %><br>

			<%= f.label :image %>
			<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "noimage.png", size:'100x100' %>
			<%= f.attachment_field :profile_image, class: "mb-10px" %>

			<%= f.label :Introduction %>
			<%= f.text_area :introduction, class: "mb-10px" %><br>

			<%= f.submit "Update User", class: "mb-10px" %>
		<% end %>

app/views/users/index.html.erb
<div class="row">

	<div class="urinfo col-xs-3">
		<h2>User info</h2>
			<%= render 'users/info', user: @user %>
		<h2>New book</h2>
			<%= render 'books/form', book: @book %>
	</div>

	<div class="otherinfo col-xs-9">
		<h2>Users</h2>
		<%= render 'index', users: @users %>
	</div><!-- /.urbooks -->

</div>

app/views/users/show.html.erb
	<% if flash[:notice] %><p><%= flash[:notice] %></p><% end %>

		<div class="row">
			<div class="urinfo col-xs-3">
				<h2>User info</h2>
					<%= render 'users/info', user: @user %>
				<h2>New book</h2>
					<%= render 'books/form', book: @book %>
			</div>
			<div class="urbooks col-xs-9">
				<h2>Books</h2>

				<table class="table">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
						</tr>
					</thead>
					<tbody>
						<% @books.each do |book| %>
						<tr>
							<td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "noimage.png", size:'40x40' %></td>
							<td><%= link_to book.title, book_path(book) %></td>
							<td><%= book.body %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div><!-- /.urbooks -->
		</div>

<!-- 住所のマップ -->
	<% if @user == current_user %>
	  <h2>Your MAP</h2>
	  <div id='map' class="<%= @user.prefecture_code + @user.city + @user.street %>" style="height: 400px;"></div>
	<% end %>

	<script>

	// mapを関数の外で定義(codeAddressでも使うため)


	let map
	let geocoder

	function initMap(){
	  // geocoderを初期化
	  geocoder = new google.maps.Geocoder()
	  geocoder.geocode( { 'address': $('#map').attr('class')}, function(results, status) {
	    if (status == 'OK') {
	　　　　　　　　　　　　// map.setCenterで地図が移動[0]は配列の一番目
	      map.setCenter(results[0].geometry.location);

	　　　　　　　　　　　　// google.maps.Markerでーカが立つ
	      var marker = new google.maps.Marker({
	          map: map,
	          position: results[0].geometry.location
	      });
	    } else {
	      alert('Geocode was not successful for the following reason: ' + status);
	    }
	  });
	  // 初期ポジション
	  map = new google.maps.Map(document.getElementById('map'), {
	  center: {lat: -34.397, lng: 150.644},
	  zoom: 8
	  });
	}
	</script>
	<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['SECRET_KEY'] %>&callback=initMap" async defer></script>
<!-- 住所のマップ -->

app/views/users/show_follow.html.erb
<h2>Follow User</h2>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.followings.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "noimage.png", size:'40' %></td>
      <td><%= user.name %></td>
      <td><%= "フォロー数#{user.followings.count}" %></td>
      <td><%= "フォロワー数#{user.followers.count}" %></td>
      <td></td>
      <td><%= link_to "詳細", user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show_follower.html.erb
<h2>Follower User</h2>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.followers.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "noimage.png", size:'40' %></td>
      <td><%= user.name %></td>
      <td><%= "フォロー数#{user.followings.count}" %></td>
      <td><%= "フォロワー数#{user.followers.count}" %></td>
      <td></td>
      <td><%= link_to "詳細", user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>