config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about' => 'home#about'
  get 'search' => 'searches#search'
  get 'searches/search'
  get 'chat/:id' => 'chat#show', as: 'chat'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :chats, only: [:create]

  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:destroy, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  attachment :profile_image

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
	def favorited_by?(user)
	    favorites.where(user_id: user.id).exists?
	end

  def self.search(search, word)
    if search == "perfect_match"
      @book = Book.where(title: "#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	validates :comment, presence: true
	belongs_to :user
    belongs_to :book
end

# <% if @user.errors.any? %>
#   <div id="error_explanation">
#       <h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
#     <ul>
#       <% @user.errors.full_messages.each do |message| %>
#         <li><%= message %></li>
#       <% end %>
#     </ul>
#   </div>
# <% end %>

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  #validates :follower_id, presence: true
  #validates :following_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

# バリデーション
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  # validates :postcode, presence: true
  # validates :prefecture_code, presence: true
  # validates :city, presence: true
  # validates :street, presence: true
# バリデーション

# アソシエーション
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id",
                                     class_name: "Relationship",
                                     dependent: :destroy
  has_many :follower_relationships, foreign_key: "following_id",
                                    class_name: "Relationship",
                                    dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :followers, through: :follower_relationships
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
# アソシエーション


# follow関連
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
# follow関連


  def self.search(search, word)
    if search == "perfect_match"
      @user = User.where(name: "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    else
      @user = User.all
    end
  end

  include JpPrefecture
  jp_prefecture :prefecture_code
  # def prefecture_name
  #   JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  # end

  # def prefecture_name=(prefecture_name)
  #   self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  # end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user_book?, only: [:edit, :update]
  def ensure_current_user_book?
    book = Book.find(params[:id])
    redirect_to books_path unless current_user.id == book.user_id
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_comments = @book.book_comments.order("id DESC")
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :profile_image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
     user == current_user
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>

    <%= form_tag(search_path, method: :get) do %>

    <%= select_tag 'range' ,options_for_select([['---選択してください---', ''], ['User', '1'], ['Book', '2']]) %>

    <%= select_tag 'search', options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"], ["前方一致","forward_match"], ["後方一致","backward_match"]]) %>
    <%= text_field_tag (:word) %>
    <%= submit_tag "検索" %>

    <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//jpostal-1006.appspot.com/jquery.jpostal.js"></script>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left"><span>Bookers</span></nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
              <li><%= link_to " Users", users_path, class: "glyphicon glyphicon-user" %></li>
              <li><%= link_to " Books", books_path, class: "glyphicon glyphicon-book" %></li>
              <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %></li>
            <% else %>
              <li><%= link_to " Home", root_path, class: "glyphicon glyphicon-home" %></li>
              <li><%= link_to " About", home_about_path, class: "glyphicon glyphicon-link" %></li>
              <li><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %></li>
              <li><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
            <% end %>
          </ul><!-- /.navbar-rigth -->
        </nav>
      </div><!-- /.container -->
    </header>
    <div class="body">
      <div class="container">
        <%= render 'layouts/search' %>
        <%= yield %>
      </div><!-- /.container -->
    </div><!-- /.body -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p class="copyright">CopyRight Infratop.inc</p>
          </div><!-- /.col-xs-3 col-xs-offset-9 -->
        </div><!-- /.row -->
      </div><!-- /.container -->
    </footer>
  </body>
</html>